{
 "title": "Monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Balance Search Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Tenant: alpha",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "balance_search_requests_total{tenant=\"alpha\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Tenant: beta",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "balance_search_requests_total{tenant=\"beta\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Tenant: gamma",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "balance_search_requests_total{tenant=\"gamma\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  { "title": "Total Payment Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Tenant: alpha",
   "type": "piechart",
   "description": "Request status of /transfer endpoint",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "payments_requests_total{route=\"/transfer\", host=\"alpha.kclab.site\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Tenant: beta",
   "type": "piechart",
   "description": "Request status of /transfer endpoint",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "payments_requests_total{route=\"/transfer\", host=\"beta.kclab.site\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Tenant: gamma",
   "type": "piechart",
   "description": "Request status of /transfer endpoint",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "payments_requests_total{route=\"/transfer\", host=\"gamma.kclab.site\"}",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}