Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.box_version = "202510.26.0"

  # Use an external script. It will run as root user.
  config.vm.provision "shell", path: "provision.sh", privileged: false
  
end
